version: 2.0
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.10
      - image: library/mysql:5.7.20
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
    steps:
      - checkout
      - restore_cache:
          key: v2-cache
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: v2-cache
          paths:
            - ~/.stack
      - run: stack install --test --no-terminal --system-ghc

workflows:
  version: 2
  build:
    jobs:
      - build
